<a href="https://colab.research.google.com/github/A-ghori/sklearn/blob/recovery/Date_Time.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import numpy as np
import pandas as pd

date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

date.head(2)

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157

In [64]:
time.head(2)

                  date                                               msg
0  2013-12-15 00:50:00                          ищу на сегодня мужика 37
1  2014-04-29 23:40:00  ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826

In [65]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [66]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [67]:
## See that when I run date.info i can see that date is stored as an object so i cant extract month,day,year etc from this date object so i need to convert this object into actual date
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [68]:
time['date'] = pd.to_datetime(time['date'])
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

## How can you extract year from a date

In [69]:
date['date_year'] = date['date'].dt.year
date.head(2)

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018

## How can you extract Month from a date

In [70]:
date['date_month'] = date['date'].dt.month
date.head(2)

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8

## How can you extract Day from a date

In [71]:
date['date_day'] = date['date'].dt.day
date.head(2)

        date  product_id  city_id  orders  date_year  date_month  date_day
0 2019-12-10        5628       25       3       2019          12        10
1 2018-08-15        3646       14     157       2018           8        15

## How can you extract Month_Name from a date

In [72]:
date['date_month_name'] = date['date'].dt.month_name()
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name
0,2019-12-10,5628,25,3,2019,12,10,December
1,2018-08-15,3646,14,157,2018,8,15,August

## How can you extract week of that date

In [73]:
date['date_week'] = date['date'].dt.day_of_week
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week
0,2019-12-10,5628,25,3,2019,12,10,December,1
1,2018-08-15,3646,14,157,2018,8,15,August,2

## day of the week - name

In [74]:
date['date_name'] = date['date'].dt.day_name()
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_name
0,2019-12-10,5628,25,3,2019,12,10,December,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,15,August,2,Wednesday

## is weekend ?

In [75]:
date['date_weekend'] = np.where(date['date_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month,date_day,date_month_name,date_week,date_name,date_weekend
0,2019-12-10,2019,12,10,December,1,Tuesday,0
1,2018-08-15,2018,8,15,August,2,Wednesday,0
2,2018-10-23,2018,10,23,October,1,Tuesday,0
3,2019-08-17,2019,8,17,August,5,Saturday,1
4,2019-01-06,2019,1,6,January,6,Sunday,1

# Extract week of the year

In [80]:
date['date_week'] = date['date'].dt.isocalendar().week
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_name,date_weekend
0,2019-12-10,5628,25,3,2019,12,10,December,50,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,15,August,33,Wednesday,0

## extract quater

In [82]:
date['quarter'] = date['date'].dt.quarter
date.head(2)

,date,product_id,city_id,orders,date_year,date_month,date_day,date_month_name,date_week,date_name,date_weekend,quarter
0,2019-12-10,5628,25,3,2019,12,10,December,50,Tuesday,0,4
1,2018-08-15,3646,14,157,2018,8,15,August,33,Wednesday,0,3

## Etract Time elapsed betweem dates

In [84]:
import datetime

today = datetime.datetime.today()

today


#2026    → Year
#9       → Month (September)
#5       → Day
#13      → Hour (1 PM)
#54      → Minute
#28      → Second
#415284  → Microsecond

datetime.datetime(2026, 9, 5, 13, 56, 7, 593082)

In [88]:
today - date['date']

0     0 days
1     0 days
2     0 days
3     0 days
4     0 days
       ...
995   0 days
996   0 days
997   0 days
998   0 days
999   0 days
Name: date, Length: 1000, dtype: timedelta64[ns]

In [89]:
(today - date['date']).dt.days

0      0
1      0
2      0
3      0
4      0
      ..
995    0
996    0
997    0
998    0
999    0
Name: date, Length: 1000, dtype: int64

In [91]:
## Month Passed
np.round((today -date['date']) / np.timedelta64(1,'m'),0)

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ...
995    0.0
996    0.0
997    0.0
998    0.0
999    0.0
Name: date, Length: 1000, dtype: float64

In [92]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [94]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [96]:
today - time['date']

0     2185 days 23:10:00
1     1568 days 00:20:00
2     2122 days 23:39:00
3     1722 days 23:29:00
4     1897 days 00:49:00
             ...
995   2396 days 23:10:00
996   1777 days 00:46:00
997   2394 days 00:23:00
998   2445 days 00:26:00
999   1943 days 00:35:00
Name: date, Length: 1000, dtype: timedelta64[ns]